/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        coral: {
          DEFAULT: "#FF6B6B",
          50: "#FFF0F0",
          100: "#FFE0E0",
          200: "#FFC4C4",
          300: "#FF9B9B",
          400: "#FF8E8E",
          500: "#FF6B6B",
          600: "#E55A5A",
          700: "#CC4A4A",
          800: "#B33B3B",
          900: "#992C2C",
        },
        teal: {
          DEFAULT: "#4ECDC4",
          50: "#F0FCFB",
          100: "#E0F8F6",
          200: "#C4F0EC",
          300: "#9BE5DE",
          400: "#6EE0D8",
          500: "#4ECDC4",
          600: "#3DB8B0",
          700: "#2CA39C",
          800: "#1B8E88",
          900: "#0A7974",
        },
        sky: {
          DEFAULT: "#45B7D1",
          50: "#F0F9FC",
          100: "#E0F3F8",
          200: "#C4E7F0",
          300: "#9BD5E8",
          400: "#6EC3E0",
          500: "#45B7D1",
          600: "#34A2C4",
          700: "#238DB7",
          800: "#1278AA",
          900: "#01639D",
        },
        gold: {
          DEFAULT: "#FFD700",
          50: "#FFFBE6",
          100: "#FFF7CC",
          200: "#FFEF99",
          300: "#FFE766",
          400: "#FFDF33",
          500: "#FFD700",
          600: "#E6C200",
          700: "#CCAD00",
          800: "#B39900",
          900: "#998400",
        },
        dark: {
          DEFAULT: "#0A0A0F",
          100: "#12121A",
          200: "#1A1A24",
          300: "#222230",
          400: "#2A2A3C",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glow: "0 0 30px rgba(255, 107, 107, 0.4)",
        "glow-teal": "0 0 30px rgba(78, 205, 196, 0.4)",
        "glow-sky": "0 0 30px rgba(69, 183, 209, 0.4)",
        "3d": "0 25px 50px -12px rgba(0, 0, 0, 0.5)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
